// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejzcygffweuuczsonzsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqemN5Z2Zmd2V1dWN6c29uenNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDkxNjYsImV4cCI6MjA2NzEyNTE2Nn0.ZXOXf7UxUMxOrCbWF3EFSKNB6x63r_lVdsHeRDXuIQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});